<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>The EMU-SDMS Manual</title>
  <meta name="description" content="The EMU-SDMS Manual">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="The EMU-SDMS Manual" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://ips-lmu.github.io/The-EMU-SDMS-Manual/" />
  <meta property="og:image" content="https://ips-lmu.github.io/The-EMU-SDMS-Manual/pics/EMU-webAppIcon-roundCorners.png" />
  <meta property="og:description" content="The EMU-SDMS Manual" />
  <meta name="github-repo" content="IPS-LMU/The-EMU-SDMS-Manual" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="The EMU-SDMS Manual" />
  
  <meta name="twitter:description" content="The EMU-SDMS Manual" />
  <meta name="twitter:image" content="https://ips-lmu.github.io/The-EMU-SDMS-Manual/pics/EMU-webAppIcon-roundCorners.png" />

<meta name="author" content="Raphael Winkelmann">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="chap-emu-webApp.html">
<link rel="next" href="chap-querysys-impl.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The EMU-SDMS Manual</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="installing-the-emu-sdms.html"><a href="installing-the-emu-sdms.html"><i class="fa fa-check"></i><b>1</b> Installing the EMU-SDMS</a><ul>
<li class="chapter" data-level="1.1" data-path="installing-the-emu-sdms.html"><a href="installing-the-emu-sdms.html#version-disclaimer"><i class="fa fa-check"></i><b>1.1</b> Version disclaimer</a></li>
<li class="chapter" data-level="1.2" data-path="installing-the-emu-sdms.html"><a href="installing-the-emu-sdms.html#for-developers-and-people-interested-in-the-source-code"><i class="fa fa-check"></i><b>1.2</b> For developers and people interested in the source code</a></li>
</ul></li>
<li class="part"><span><b>I Overview and tutorial</b></span></li>
<li class="chapter" data-level="2" data-path="chap-overview.html"><a href="chap-overview.html"><i class="fa fa-check"></i><b>2</b> An overview of the EMU-SDMS</a><ul>
<li class="chapter" data-level="2.1" data-path="chap-overview.html"><a href="chap-overview.html#the-evolution-of-the-emu-sdms"><i class="fa fa-check"></i><b>2.1</b> The evolution of the EMU-SDMS</a></li>
<li class="chapter" data-level="2.2" data-path="chap-overview.html"><a href="chap-overview.html#sec:overview-sysArch"><i class="fa fa-check"></i><b>2.2</b> EMU-SDMS: System architecture and default workflow</a></li>
<li class="chapter" data-level="2.3" data-path="chap-overview.html"><a href="chap-overview.html#emu-sdms-is-it-something-for-you"><i class="fa fa-check"></i><b>2.3</b> EMU-SDMS: Is it something for you?</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-tutorial.html"><a href="chap-tutorial.html"><i class="fa fa-check"></i><b>3</b> A tutorial on how to use the EMU-SDMS</a><ul>
<li class="chapter" data-level="3.1" data-path="chap-tutorial.html"><a href="chap-tutorial.html#converting-the-textgrid-collection"><i class="fa fa-check"></i><b>3.1</b> Converting the TextGrid collection</a></li>
<li class="chapter" data-level="3.2" data-path="chap-tutorial.html"><a href="chap-tutorial.html#loading-and-inspecting-the-database"><i class="fa fa-check"></i><b>3.2</b> Loading and inspecting the database</a><ul>
<li class="chapter" data-level="3.2.1" data-path="chap-tutorial.html"><a href="chap-tutorial.html#overview"><i class="fa fa-check"></i><b>3.2.1</b> Overview</a></li>
<li class="chapter" data-level="3.2.2" data-path="chap-tutorial.html"><a href="chap-tutorial.html#database-annotation-and-visual-inspection"><i class="fa fa-check"></i><b>3.2.2</b> Database annotation and visual inspection</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chap-tutorial.html"><a href="chap-tutorial.html#querying-and-autobuilding-the-annotation-structure"><i class="fa fa-check"></i><b>3.3</b> Querying and autobuilding the annotation structure</a></li>
<li class="chapter" data-level="3.4" data-path="chap-tutorial.html"><a href="chap-tutorial.html#autobuilding"><i class="fa fa-check"></i><b>3.4</b> Autobuilding</a><ul>
<li class="chapter" data-level="3.4.1" data-path="chap-tutorial.html"><a href="chap-tutorial.html#querying-the-hierarchical-annotations"><i class="fa fa-check"></i><b>3.4.1</b> Querying the hierarchical annotations</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="chap-tutorial.html"><a href="chap-tutorial.html#section:tutorial-sigExtrAndExpl"><i class="fa fa-check"></i><b>3.5</b> Signal extraction and exploration</a></li>
<li class="chapter" data-level="3.6" data-path="chap-tutorial.html"><a href="chap-tutorial.html#vowel-height-as-a-function-of-word-types-content-vs.function-evaluation-and-statistical-analysis"><i class="fa fa-check"></i><b>3.6</b> Vowel height as a function of word types (content vs. function): evaluation and statistical analysis</a></li>
<li class="chapter" data-level="3.7" data-path="chap-tutorial.html"><a href="chap-tutorial.html#conclusion"><i class="fa fa-check"></i><b>3.7</b> Conclusion</a></li>
</ul></li>
<li class="part"><span><b>II Main components and concepts</b></span></li>
<li class="chapter" data-level="4" data-path="chap-annot-struct-mod.html"><a href="chap-annot-struct-mod.html"><i class="fa fa-check"></i><b>4</b> Annotation Structure Modeling</a><ul>
<li class="chapter" data-level="4.1" data-path="chap-annot-struct-mod.html"><a href="chap-annot-struct-mod.html#per-database-annotation-structure-definition"><i class="fa fa-check"></i><b>4.1</b> Per database annotation structure definition</a></li>
<li class="chapter" data-level="4.2" data-path="chap-annot-struct-mod.html"><a href="chap-annot-struct-mod.html#parallel-labels-and-multiple-attributes"><i class="fa fa-check"></i><b>4.2</b> Parallel labels and multiple attributes</a></li>
<li class="chapter" data-level="4.3" data-path="chap-annot-struct-mod.html"><a href="chap-annot-struct-mod.html#metadata-strategy-using-single-bundle-root-nodes"><i class="fa fa-check"></i><b>4.3</b> Metadata strategy using single bundle root nodes</a></li>
<li class="chapter" data-level="4.4" data-path="chap-annot-struct-mod.html"><a href="chap-annot-struct-mod.html#conclusion-1"><i class="fa fa-check"></i><b>4.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-emuDB.html"><a href="chap-emuDB.html"><i class="fa fa-check"></i><b>5</b> The <code>emuDB</code> Format</a><ul>
<li class="chapter" data-level="5.1" data-path="chap-emuDB.html"><a href="chap-emuDB.html#database-design"><i class="fa fa-check"></i><b>5.1</b> Database design</a></li>
<li class="chapter" data-level="5.2" data-path="chap-emuDB.html"><a href="chap-emuDB.html#creating-an-emudb"><i class="fa fa-check"></i><b>5.2</b> Creating an <code>emuDB</code></a><ul>
<li class="chapter" data-level="5.2.1" data-path="chap-emuDB.html"><a href="chap-emuDB.html#creating-an-emudb-from-scratch"><i class="fa fa-check"></i><b>5.2.1</b> Creating an <code>emuDB</code> from scratch</a></li>
<li class="chapter" data-level="5.2.2" data-path="chap-emuDB.html"><a href="chap-emuDB.html#loading-and-editing-an-empty-database"><i class="fa fa-check"></i><b>5.2.2</b> Loading and editing an empty database</a></li>
<li class="chapter" data-level="5.2.3" data-path="chap-emuDB.html"><a href="chap-emuDB.html#level-definitions"><i class="fa fa-check"></i><b>5.2.3</b> Level definitions</a></li>
<li class="chapter" data-level="5.2.4" data-path="chap-emuDB.html"><a href="chap-emuDB.html#link-definitions"><i class="fa fa-check"></i><b>5.2.4</b> Link definitions</a></li>
<li class="chapter" data-level="5.2.5" data-path="chap-emuDB.html"><a href="chap-emuDB.html#file-handling"><i class="fa fa-check"></i><b>5.2.5</b> File handling</a></li>
<li class="chapter" data-level="5.2.6" data-path="chap-emuDB.html"><a href="chap-emuDB.html#ssff-track-definitions"><i class="fa fa-check"></i><b>5.2.6</b> SSFF track definitions</a></li>
<li class="chapter" data-level="5.2.7" data-path="chap-emuDB.html"><a href="chap-emuDB.html#configuring-the-emu-webapp-and-annotating-the-emudb"><i class="fa fa-check"></i><b>5.2.7</b> Configuring the <code>EMU-webApp</code> and annotating the <code>emuDB</code></a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="chap-emuDB.html"><a href="chap-emuDB.html#conclusion-2"><i class="fa fa-check"></i><b>5.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-querysys.html"><a href="chap-querysys.html"><i class="fa fa-check"></i><b>6</b> The query system</a><ul>
<li class="chapter" data-level="6.1" data-path="chap-querysys.html"><a href="chap-querysys.html#sec:query-emuRsegs"><i class="fa fa-check"></i><b>6.1</b> <code>emuRsegs</code>: The resulting object of a query</a></li>
<li class="chapter" data-level="6.2" data-path="chap-querysys.html"><a href="chap-querysys.html#eql-the-emu-query-language-version-2"><i class="fa fa-check"></i><b>6.2</b> <code>EQL</code>: The EMU Query Language version 2</a><ul>
<li class="chapter" data-level="6.2.1" data-path="chap-querysys.html"><a href="chap-querysys.html#simple-queries"><i class="fa fa-check"></i><b>6.2.1</b> Simple queries</a></li>
<li class="chapter" data-level="6.2.2" data-path="chap-querysys.html"><a href="chap-querysys.html#combining-simple-queries"><i class="fa fa-check"></i><b>6.2.2</b> Combining simple queries</a></li>
<li class="chapter" data-level="6.2.3" data-path="chap-querysys.html"><a href="chap-querysys.html#subsec:query_positionQueries"><i class="fa fa-check"></i><b>6.2.3</b> Position queries</a></li>
<li class="chapter" data-level="6.2.4" data-path="chap-querysys.html"><a href="chap-querysys.html#subsec:query_countQueries"><i class="fa fa-check"></i><b>6.2.4</b> Count queries</a></li>
<li class="chapter" data-level="6.2.5" data-path="chap-querysys.html"><a href="chap-querysys.html#subsec:query_moreComplexQueries"><i class="fa fa-check"></i><b>6.2.5</b> More complex queries</a></li>
<li class="chapter" data-level="6.2.6" data-path="chap-querysys.html"><a href="chap-querysys.html#subsec:query_deducingTime"><i class="fa fa-check"></i><b>6.2.6</b> Deducing time</a></li>
<li class="chapter" data-level="6.2.7" data-path="chap-querysys.html"><a href="chap-querysys.html#subsec:requery"><i class="fa fa-check"></i><b>6.2.7</b> Requery</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="chap-querysys.html"><a href="chap-querysys.html#discussion"><i class="fa fa-check"></i><b>6.3</b> Discussion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-sigDataExtr.html"><a href="chap-sigDataExtr.html"><i class="fa fa-check"></i><b>7</b> Signal data extraction</a><ul>
<li class="chapter" data-level="7.1" data-path="chap-sigDataExtr.html"><a href="chap-sigDataExtr.html#extracting-pre-defined-tracks"><i class="fa fa-check"></i><b>7.1</b> Extracting pre-defined tracks</a></li>
<li class="chapter" data-level="7.2" data-path="chap-sigDataExtr.html"><a href="chap-sigDataExtr.html#adding-new-tracks"><i class="fa fa-check"></i><b>7.2</b> Adding new tracks</a></li>
<li class="chapter" data-level="7.3" data-path="chap-sigDataExtr.html"><a href="chap-sigDataExtr.html#calculating-tracks-on-the-fly"><i class="fa fa-check"></i><b>7.3</b> Calculating tracks on-the-fly</a></li>
<li class="chapter" data-level="7.4" data-path="chap-sigDataExtr.html"><a href="chap-sigDataExtr.html#the-resulting-object-trackdata-vs.-emurtrackdata"><i class="fa fa-check"></i><b>7.4</b> The resulting object: <code>trackdata</code> vs. <code>emuRtrackdata</code></a></li>
<li class="chapter" data-level="7.5" data-path="chap-sigDataExtr.html"><a href="chap-sigDataExtr.html#conclusion-3"><i class="fa fa-check"></i><b>7.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap-wrassp.html"><a href="chap-wrassp.html"><i class="fa fa-check"></i><b>8</b> The R package <code>wrassp</code></a><ul>
<li class="chapter" data-level="8.1" data-path="chap-wrassp.html"><a href="chap-wrassp.html#introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="chap-wrassp.html"><a href="chap-wrassp.html#file-i0-and-the-asspdataobj"><i class="fa fa-check"></i><b>8.2</b> File I/0 and the <code>AsspDataObj</code></a></li>
<li class="chapter" data-level="8.3" data-path="chap-wrassp.html"><a href="chap-wrassp.html#signal-processing"><i class="fa fa-check"></i><b>8.3</b> Signal processing</a></li>
<li class="chapter" data-level="8.4" data-path="chap-wrassp.html"><a href="chap-wrassp.html#subsec:wrassp-wrasspOutputInfos"><i class="fa fa-check"></i><b>8.4</b> The <code>wrasspOutputInfos</code> object</a></li>
<li class="chapter" data-level="8.5" data-path="chap-wrassp.html"><a href="chap-wrassp.html#subsec:wrassp-formants"><i class="fa fa-check"></i><b>8.5</b> Formants and their bandwidths</a><ul>
<li class="chapter" data-level="8.5.1" data-path="chap-wrassp.html"><a href="chap-wrassp.html#subsec:wrassp_f0"><i class="fa fa-check"></i><b>8.5.1</b> Fundamental frequency contour</a></li>
<li class="chapter" data-level="8.5.2" data-path="chap-wrassp.html"><a href="chap-wrassp.html#subsec:wrassp-RMS"><i class="fa fa-check"></i><b>8.5.2</b> RMS energy contour</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="chap-wrassp.html"><a href="chap-wrassp.html#sec:wrassp_logging"><i class="fa fa-check"></i><b>8.6</b> Logging <code>wrassp</code>’s function calls</a></li>
<li class="chapter" data-level="8.7" data-path="chap-wrassp.html"><a href="chap-wrassp.html#sec:wrassp_emu-sdms"><i class="fa fa-check"></i><b>8.7</b> Using <code>wrassp</code> in the EMU-SDMS</a></li>
<li class="chapter" data-level="8.8" data-path="chap-wrassp.html"><a href="chap-wrassp.html#sec:wrassp_genSSFF"><i class="fa fa-check"></i><b>8.8</b> Storing data in the SSFF file format</a></li>
<li class="chapter" data-level="8.9" data-path="chap-wrassp.html"><a href="chap-wrassp.html#conclusion-4"><i class="fa fa-check"></i><b>8.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html"><i class="fa fa-check"></i><b>9</b> The <code>EMU-webApp</code></a><ul>
<li class="chapter" data-level="9.1" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#sec:emu-webApp-mainLayout"><i class="fa fa-check"></i><b>9.1</b> Main layout</a></li>
<li class="chapter" data-level="9.2" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#sec:webApp-generalUsage"><i class="fa fa-check"></i><b>9.2</b> General usage</a><ul>
<li class="chapter" data-level="9.2.1" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#annotating-levels-containing-time-information"><i class="fa fa-check"></i><b>9.2.1</b> Annotating levels containing time information</a></li>
<li class="chapter" data-level="9.2.2" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#working-with-hierarchical-annotations-2-chapemu-webapp"><i class="fa fa-check"></i><b>9.2.2</b> Working with hierarchical annotations</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#configuring-the-emu-webapp"><i class="fa fa-check"></i><b>9.3</b> Configuring the <code>EMU-webApp</code></a><ul>
<li class="chapter" data-level="9.3.1" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#subsec:emu-webAppConfigWithEmuR"><i class="fa fa-check"></i><b>9.3.1</b> Basic configurations using <code>emuR</code></a></li>
<li class="chapter" data-level="9.3.2" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#signal-canvas-and-level-canvas-order"><i class="fa fa-check"></i><b>9.3.2</b> Signal canvas and level canvas order</a></li>
<li class="chapter" data-level="9.3.3" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#subsec:emu-webAppAdvancedConfig"><i class="fa fa-check"></i><b>9.3.3</b> Advanced configurations made by editing the <code>_DBconfig.json</code></a></li>
<li class="chapter" data-level="9.3.4" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#d-canvas"><i class="fa fa-check"></i><b>9.3.4</b> 2D canvas</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="chap-emu-webApp.html"><a href="chap-emu-webApp.html#conclusion-5"><i class="fa fa-check"></i><b>9.4</b> Conclusion</a></li>
</ul></li>
<li class="part"><span><b>III Main <code>emuR</code> function and object index</b></span></li>
<li class="chapter" data-level="10" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html"><i class="fa fa-check"></i><b>10</b> <code>emuR</code> - package functions</a><ul>
<li class="chapter" data-level="10.1" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-importRoutines"><i class="fa fa-check"></i><b>10.1</b> Import and conversion routines</a><ul>
<li class="chapter" data-level="10.1.1" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#legacy-emu-databases"><i class="fa fa-check"></i><b>10.1.1</b> Legacy EMU databases</a></li>
<li class="chapter" data-level="10.1.2" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#textgrid-collections"><i class="fa fa-check"></i><b>10.1.2</b> TextGrid collections</a></li>
<li class="chapter" data-level="10.1.3" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#bpf-collections"><i class="fa fa-check"></i><b>10.1.3</b> BPF collections</a></li>
<li class="chapter" data-level="10.1.4" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#txt-collections"><i class="fa fa-check"></i><b>10.1.4</b> txt collections</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-emuDBinteract"><i class="fa fa-check"></i><b>10.2</b> <code>emuDB</code> interaction and configuration routines</a></li>
<li class="chapter" data-level="10.3" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-emuWebAppConfig"><i class="fa fa-check"></i><b>10.3</b> <code>EMU-webApp</code> configuration routines</a></li>
<li class="chapter" data-level="10.4" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-dataExtr"><i class="fa fa-check"></i><b>10.4</b> Data extraction routines</a></li>
<li class="chapter" data-level="10.5" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-centralObjects"><i class="fa fa-check"></i><b>10.5</b> Central objects</a></li>
<li class="chapter" data-level="10.6" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-exportRoutines"><i class="fa fa-check"></i><b>10.6</b> Export routines</a></li>
<li class="chapter" data-level="10.7" data-path="chap-emuRpackageDetails.html"><a href="chap-emuRpackageDetails.html#conclusion-6"><i class="fa fa-check"></i><b>10.7</b> Conclusion</a></li>
</ul></li>
<li class="part"><span><b>IV Implementation</b></span></li>
<li class="chapter" data-level="11" data-path="chap-querysys-impl.html"><a href="chap-querysys-impl.html"><i class="fa fa-check"></i><b>11</b> Implementation of the query system</a><ul>
<li class="chapter" data-level="11.1" data-path="chap-querysys-impl.html"><a href="chap-querysys-impl.html#sec:query-queryExpressionParser"><i class="fa fa-check"></i><b>11.1</b> Query expression parser</a></li>
<li class="chapter" data-level="11.2" data-path="chap-querysys-impl.html"><a href="chap-querysys-impl.html#subsec:query-redundantLinks"><i class="fa fa-check"></i><b>11.2</b> Redundant links</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="chap-wrassp-impl.html"><a href="chap-wrassp-impl.html"><i class="fa fa-check"></i><b>12</b> <code>wrassp</code> implementation</a><ul>
<li class="chapter" data-level="12.1" data-path="chap-wrassp-impl.html"><a href="chap-wrassp-impl.html#the-libassp-port"><i class="fa fa-check"></i><b>12.1</b> The <code>libassp</code> port</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap-emu-webAppImplementation.html"><a href="chap-emu-webAppImplementation.html"><i class="fa fa-check"></i><b>13</b> <code>EMU-webApp</code> implementation</a><ul>
<li class="chapter" data-level="13.1" data-path="chap-emu-webAppImplementation.html"><a href="chap-emu-webAppImplementation.html#subsec:emu-webAppTheProtocol"><i class="fa fa-check"></i><b>13.1</b> Communication protocol</a></li>
<li class="chapter" data-level="13.2" data-path="chap-emu-webAppImplementation.html"><a href="chap-emu-webAppImplementation.html#url-parameters"><i class="fa fa-check"></i><b>13.2</b> URL parameters</a><ul>
<li class="chapter" data-level="13.2.1" data-path="chap-emu-webAppImplementation.html"><a href="chap-emu-webAppImplementation.html#websocket-server-parameters"><i class="fa fa-check"></i><b>13.2.1</b> Websocket server parameters</a></li>
<li class="chapter" data-level="13.2.2" data-path="chap-emu-webAppImplementation.html"><a href="chap-emu-webAppImplementation.html#examples"><i class="fa fa-check"></i><b>13.2.2</b> Examples</a></li>
<li class="chapter" data-level="13.2.3" data-path="chap-emu-webAppImplementation.html"><a href="chap-emu-webAppImplementation.html#label-file-preview-parameters"><i class="fa fa-check"></i><b>13.2.3</b> Label file preview parameters</a></li>
<li class="chapter" data-level="13.2.4" data-path="chap-emu-webAppImplementation.html"><a href="chap-emu-webAppImplementation.html#examples-1"><i class="fa fa-check"></i><b>13.2.4</b> Examples</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Appendices</b></span></li>
<li class="chapter" data-level="14" data-path="app-chap-useCases.html"><a href="app-chap-useCases.html"><i class="fa fa-check"></i><b>14</b> Use cases</a><ul>
<li class="chapter" data-level="14.1" data-path="app-chap-useCases.html"><a href="app-chap-useCases.html#sec:app-chap-useCases-q1"><i class="fa fa-check"></i><b>14.1</b> What is the average length of all <em>n</em> phonetic segments in the <em>ae</em> <code>emuDB</code>?</a></li>
<li class="chapter" data-level="14.2" data-path="app-chap-useCases.html"><a href="app-chap-useCases.html#sec:app-chap-useCases-q2"><i class="fa fa-check"></i><b>14.2</b> What does the F1 and F2 distribution of all phonetic segments that contain the labels <em>I</em>, <em>o:</em>, <em>u:</em>, <em>V</em> or <em>@</em> look like?</a></li>
<li class="chapter" data-level="14.3" data-path="app-chap-useCases.html"><a href="app-chap-useCases.html#sec:app-chap-useCases-q3"><i class="fa fa-check"></i><b>14.3</b> What words do the phonetic segments that carry the labels <em>s</em>, <em>z</em>, <em>S</em> or <em>Z</em> in the <em>ae</em> <code>emuDB</code> occur in and what is their phonetic context?</a></li>
<li class="chapter" data-level="14.4" data-path="app-chap-useCases.html"><a href="app-chap-useCases.html#sec:app-chap-useCases-q4"><i class="fa fa-check"></i><b>14.4</b> Do the phonetic segments labeled <em>s</em>, <em>z</em>, <em>S</em> or <em>Z</em> in the <em>ae</em> <code>emuDB</code> differ with respect to their first spectral moment?\footnote{The original version of this use case was written by Florian Schiel as part of the <code>emuR_intro</code> vignette that is part of the <code>emuR</code> package.</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="app-chap-fileFormats.html"><a href="app-chap-fileFormats.html"><i class="fa fa-check"></i><b>15</b> File Formats</a><ul>
<li class="chapter" data-level="15.1" data-path="app-chap-fileFormats.html"><a href="app-chap-fileFormats.html#file-descriptions"><i class="fa fa-check"></i><b>15.1</b> File descriptions</a><ul>
<li class="chapter" data-level="15.1.1" data-path="app-chap-fileFormats.html"><a href="app-chap-fileFormats.html#subsec:app-chapFileFormatsDBconfig"><i class="fa fa-check"></i><b>15.1.1</b> <code>_DBconfig.json</code></a></li>
<li class="chapter" data-level="15.1.2" data-path="app-chap-fileFormats.html"><a href="app-chap-fileFormats.html#subsec:app_chapFileFormatsAnnotJSON"><i class="fa fa-check"></i><b>15.1.2</b> <code>_annot.json</code></a></li>
<li class="chapter" data-level="15.1.3" data-path="app-chap-fileFormats.html"><a href="app-chap-fileFormats.html#subsec:app_chapFileFormatsSSFF"><i class="fa fa-check"></i><b>15.1.3</b> The SSFF file format</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="app-chap-fileFormats.html"><a href="app-chap-fileFormats.html#example-files"><i class="fa fa-check"></i><b>15.2</b> Example files</a><ul>
<li class="chapter" data-level="15.2.1" data-path="app-chap-fileFormats.html"><a href="app-chap-fileFormats.html#subsec:app-chapExampleFilesBundleList"><i class="fa fa-check"></i><b>15.2.1</b> <code>_bundleList.json</code></a></li>
<li class="chapter" data-level="15.2.2" data-path="app-chap-fileFormats.html"><a href="app-chap-fileFormats.html#subsec:app_chapExampleFilesBndlJSON"><i class="fa fa-check"></i><b>15.2.2</b> <code>_bndl.json</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html"><i class="fa fa-check"></i><b>16</b> The <code>EMU-webApp-websocket-protocol</code> Version 2.0</a><ul>
<li class="chapter" data-level="16.1" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#protocol-overview"><i class="fa fa-check"></i><b>16.1</b> Protocol overview</a></li>
<li class="chapter" data-level="16.2" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#protocol-commands"><i class="fa fa-check"></i><b>16.2</b> Protocol commands</a><ul>
<li class="chapter" data-level="16.2.1" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#getprotocol"><i class="fa fa-check"></i><b>16.2.1</b> <code>GETPROTOCOL</code></a></li>
<li class="chapter" data-level="16.2.2" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#getdousermanagement"><i class="fa fa-check"></i><b>16.2.2</b> <code>GETDOUSERMANAGEMENT</code></a></li>
<li class="chapter" data-level="16.2.3" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#logonuser"><i class="fa fa-check"></i><b>16.2.3</b> <code>LOGONUSER</code></a></li>
<li class="chapter" data-level="16.2.4" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#getglobaldbconfig"><i class="fa fa-check"></i><b>16.2.4</b> <code>GETGLOBALDBCONFIG</code></a></li>
<li class="chapter" data-level="16.2.5" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#getbundlelist"><i class="fa fa-check"></i><b>16.2.5</b> <code>GETBUNDLELIST</code></a></li>
<li class="chapter" data-level="16.2.6" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#getbundle"><i class="fa fa-check"></i><b>16.2.6</b> <code>GETBUNDLE</code></a></li>
<li class="chapter" data-level="16.2.7" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#savebundle"><i class="fa fa-check"></i><b>16.2.7</b> <code>SAVEBUNDLE</code></a></li>
<li class="chapter" data-level="16.2.8" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#disconnectwarning"><i class="fa fa-check"></i><b>16.2.8</b> <code>DISCONNECTWARNING</code></a></li>
<li class="chapter" data-level="16.2.9" data-path="app-chap-wsProtocol.html"><a href="app-chap-wsProtocol.html#error-handling"><i class="fa fa-check"></i><b>16.2.9</b> Error handling</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="app-chap-EQL-EBNF.html"><a href="app-chap-EQL-EBNF.html"><i class="fa fa-check"></i><b>17</b> EQL EBNF</a><ul>
<li class="chapter" data-level="17.1" data-path="app-chap-EQL-EBNF.html"><a href="app-chap-EQL-EBNF.html#terminal-symbols-of-eql2-operators-and-their-meaning"><i class="fa fa-check"></i><b>17.1</b> Terminal symbols of EQL2 (operators) and their meaning</a></li>
<li class="chapter" data-level="17.2" data-path="app-chap-EQL-EBNF.html"><a href="app-chap-EQL-EBNF.html#terminal-symbols-of-eql2-brackets-and-their-meanings."><i class="fa fa-check"></i><b>17.2</b> Terminal symbols of EQL2 (brackets) and their meanings.</a></li>
<li class="chapter" data-level="17.3" data-path="app-chap-EQL-EBNF.html"><a href="app-chap-EQL-EBNF.html#terminal-symbols-of-eql2-functions-and-their-meanings."><i class="fa fa-check"></i><b>17.3</b> Terminal symbols of EQL2 (functions) and their meanings.</a></li>
<li class="chapter" data-level="17.4" data-path="app-chap-EQL-EBNF.html"><a href="app-chap-EQL-EBNF.html#formal-description-of-emu-query-language-version-2"><i class="fa fa-check"></i><b>17.4</b> Formal description of EMU Query Language Version 2</a></li>
<li class="chapter" data-level="17.5" data-path="app-chap-EQL-EBNF.html"><a href="app-chap-EQL-EBNF.html#restrictions"><i class="fa fa-check"></i><b>17.5</b> Restrictions</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="app-chap-eql.html"><a href="app-chap-eql.html"><i class="fa fa-check"></i><b>18</b> EQL: further examples</a><ul>
<li class="chapter" data-level="18.1" data-path="app-chap-eql.html"><a href="app-chap-eql.html#simple-equality-inequality-matching-non-matching-queries-single-argument"><i class="fa fa-check"></i><b>18.1</b> Simple equality, inequality, matching and non-matching queries (single-argument)</a></li>
<li class="chapter" data-level="18.2" data-path="app-chap-eql.html"><a href="app-chap-eql.html#sequence-queries-using-the---sequence-operator"><i class="fa fa-check"></i><b>18.2</b> Sequence queries using the -&gt; sequence operator</a></li>
<li class="chapter" data-level="18.3" data-path="app-chap-eql.html"><a href="app-chap-eql.html#subsequent-sequence-queries-using-nesting-of-the---sequence-operator"><i class="fa fa-check"></i><b>18.3</b> Subsequent sequence queries using nesting of the <code>-&gt;</code> sequence operator</a></li>
<li class="chapter" data-level="18.4" data-path="app-chap-eql.html"><a href="app-chap-eql.html#conjunction-operator"><i class="fa fa-check"></i><b>18.4</b> Conjunction operator &amp;</a></li>
<li class="chapter" data-level="18.5" data-path="app-chap-eql.html"><a href="app-chap-eql.html#domination-operator-hierarchical-queries"><i class="fa fa-check"></i><b>18.5</b> Domination operator ^ (hierarchical queries)</a><ul>
<li class="chapter" data-level="18.5.1" data-path="app-chap-eql.html"><a href="app-chap-eql.html#simple-domination"><i class="fa fa-check"></i><b>18.5.1</b> Simple domination</a></li>
<li class="chapter" data-level="18.5.2" data-path="app-chap-eql.html"><a href="app-chap-eql.html#multiple-domination"><i class="fa fa-check"></i><b>18.5.2</b> Multiple domination</a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="app-chap-eql.html"><a href="app-chap-eql.html#position"><i class="fa fa-check"></i><b>18.6</b> Position</a><ul>
<li class="chapter" data-level="18.6.1" data-path="app-chap-eql.html"><a href="app-chap-eql.html#simple-usage-of-start-end-and-medial"><i class="fa fa-check"></i><b>18.6.1</b> Simple usage of <code>Start()</code>, <code>End()</code> and <code>Medial()</code></a></li>
<li class="chapter" data-level="18.6.2" data-path="app-chap-eql.html"><a href="app-chap-eql.html#position-and-boolean"><i class="fa fa-check"></i><b>18.6.2</b> Position and boolean &amp;</a></li>
<li class="chapter" data-level="18.6.3" data-path="app-chap-eql.html"><a href="app-chap-eql.html#position-and-boolean-1"><i class="fa fa-check"></i><b>18.6.3</b> Position and boolean ^</a></li>
<li class="chapter" data-level="18.6.4" data-path="app-chap-eql.html"><a href="app-chap-eql.html#count-and-boolean"><i class="fa fa-check"></i><b>18.6.4</b> Count and boolean <code>&amp;</code></a></li>
<li class="chapter" data-level="18.6.5" data-path="app-chap-eql.html"><a href="app-chap-eql.html#count-and"><i class="fa fa-check"></i><b>18.6.5</b> Count and ^</a></li>
</ul></li>
<li class="chapter" data-level="18.7" data-path="app-chap-eql.html"><a href="app-chap-eql.html#combinations"><i class="fa fa-check"></i><b>18.7</b> Combinations</a><ul>
<li class="chapter" data-level="18.7.1" data-path="app-chap-eql.html"><a href="app-chap-eql.html#and---domination-and-sequence"><i class="fa fa-check"></i><b>18.7.1</b> ^ and -&gt; (domination and sequence)</a></li>
<li class="chapter" data-level="18.7.2" data-path="app-chap-eql.html"><a href="app-chap-eql.html#and---and-domination-and-sequence-and-boolean"><i class="fa fa-check"></i><b>18.7.2</b> ^ and -&gt; and &amp; (domination and sequence and boolean &amp;)</a></li>
</ul></li>
<li class="chapter" data-level="18.8" data-path="app-chap-eql.html"><a href="app-chap-eql.html#a-few-more-questions-and-answers"><i class="fa fa-check"></i><b>18.8</b> A few more questions and answers</a></li>
<li class="chapter" data-level="18.9" data-path="app-chap-eql.html"><a href="app-chap-eql.html#differences-to-the-legacy-emu-query-language"><i class="fa fa-check"></i><b>18.9</b> Differences to the legacy EMU query language</a><ul>
<li class="chapter" data-level="18.9.1" data-path="app-chap-eql.html"><a href="app-chap-eql.html#function-call-syntax"><i class="fa fa-check"></i><b>18.9.1</b> Function call syntax</a></li>
<li class="chapter" data-level="18.9.2" data-path="app-chap-eql.html"><a href="app-chap-eql.html#empty-result"><i class="fa fa-check"></i><b>18.9.2</b> Empty result</a></li>
<li class="chapter" data-level="18.9.3" data-path="app-chap-eql.html"><a href="app-chap-eql.html#the-result-modifier-hash-tag"><i class="fa fa-check"></i><b>18.9.3</b> The result modifier hash tag <code>#</code></a></li>
<li class="chapter" data-level="18.9.4" data-path="app-chap-eql.html"><a href="app-chap-eql.html#interpretation-of-the-hash-tag-in-conjunction-operator-queries"><i class="fa fa-check"></i><b>18.9.4</b> Interpretation of the hash tag <code>#</code> in conjunction operator queries</a></li>
<li class="chapter" data-level="18.9.5" data-path="app-chap-eql.html"><a href="app-chap-eql.html#legacy-emu"><i class="fa fa-check"></i><b>18.9.5</b> legacy EMU</a></li>
</ul></li>
<li class="chapter" data-level="18.10" data-path="app-chap-eql.html"><a href="app-chap-eql.html#bugs-in-legacy-emu-function-emu.query"><i class="fa fa-check"></i><b>18.10</b> Bugs in legacy EMU function <code>emu.query()</code></a><ul>
<li class="chapter" data-level="18.10.1" data-path="app-chap-eql.html"><a href="app-chap-eql.html#alternative-labels-in-inequality-queries"><i class="fa fa-check"></i><b>18.10.1</b> Alternative labels in inequality queries</a></li>
<li class="chapter" data-level="18.10.2" data-path="app-chap-eql.html"><a href="app-chap-eql.html#legacy-emu-1"><i class="fa fa-check"></i><b>18.10.2</b> legacy EMU</a></li>
<li class="chapter" data-level="18.10.3" data-path="app-chap-eql.html"><a href="app-chap-eql.html#emur-1"><i class="fa fa-check"></i><b>18.10.3</b> emuR</a></li>
<li class="chapter" data-level="18.10.4" data-path="app-chap-eql.html"><a href="app-chap-eql.html#errors-caused-by-missing-or-superfluous-blanks-or-parentheses"><i class="fa fa-check"></i><b>18.10.4</b> Errors caused by missing or superfluous blanks or parentheses</a></li>
<li class="chapter" data-level="18.10.5" data-path="app-chap-eql.html"><a href="app-chap-eql.html#order-of-result-segment-list"><i class="fa fa-check"></i><b>18.10.5</b> Order of result segment list</a></li>
<li class="chapter" data-level="18.10.6" data-path="app-chap-eql.html"><a href="app-chap-eql.html#additional-features"><i class="fa fa-check"></i><b>18.10.6</b> Additional features</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="app-chap-wrassp.html"><a href="app-chap-wrassp.html"><i class="fa fa-check"></i><b>19</b> <code>wrassp</code></a><ul>
<li class="chapter" data-level="19.1" data-path="app-chap-wrassp.html"><a href="app-chap-wrassp.html#sec:app-chap-wrassp-praatsSigProc"><i class="fa fa-check"></i><b>19.1</b> Using Praat’s signal processing routines in the EMU-SDMS</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The EMU-SDMS Manual</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:emuRpackageDetails" class="section level1">
<h1><span class="header-section-number">10</span> <code>emuR</code> - package functions</h1>
<p>This chapter gives an overview of the essential functions and central objects provided by the <code>emuR</code> package. It is not meant as a comprehensive list of every function and object provided by <code>emuR</code>, but rather tries to group the essential functions into meaningful categories for easier navigation. The categories presented in this chapter are:</p>
<ul>
<li>Import and conversion routines (Section <a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-importRoutines">10.1</a>),</li>
<li><code>emuDB</code> interaction and configuration routines (Section <a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-emuDBinteract">10.2</a>),</li>
<li><code>EMU-webApp</code> configuration routines (Section <a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-emuWebAppConfig">10.3</a>),</li>
<li>Data extraction routines (Section <a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-dataExtr">10.4</a>),</li>
<li>Central objects in <code>emuR</code> (Section <a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-centralObjects">10.5</a>), and</li>
<li>Export routines (Section <a href="chap-emuRpackageDetails.html#sec:emuRpackageDetails-exportRoutines">10.6</a>).</li>
</ul>
<p>If a comprehensive list of every function and object provided by the <code>emuR</code> package is required, R’s <code>help()</code> function (see R Example <a href="#rexample:emuRfuncs-help"><strong>??</strong></a>) can be used.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb233-1" data-line-number="1"><span class="kw">help</span>(<span class="dt">package=</span><span class="st">&quot;emuR&quot;</span>)</a></code></pre></div>
<div id="sec:emuRpackageDetails-importRoutines" class="section level2">
<h2><span class="header-section-number">10.1</span> Import and conversion routines</h2>
<p>As most people that are starting to use the EMU-SDMS will probably already have some form of annotated data, we will first show how to convert existing data to the <code>emuDB</code> format. For a guide to creating an <code>emuDB</code> from scratch and for information about this format see Chapter <a href="chap-emuDB.html#chap:emuDB">5</a>.</p>
<div id="legacy-emu-databases" class="section level3">
<h3><span class="header-section-number">10.1.1</span> Legacy EMU databases</h3>
<p>For people transitioning to <code>emuR</code> from the legacy EMU system, <code>emuR</code> provides a function for converting existing legacy EMU databases to the new <code>emuDB</code> format. R Example <a href="#rexample:emuRpackageDetailsConvLegacy"><strong>??</strong></a> shows how to convert a legacy database that is part of the demo data provided by the <code>emuR</code> package.</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" data-line-number="1"><span class="co"># load the package</span></a>
<a class="sourceLine" id="cb234-2" data-line-number="2"><span class="kw">library</span>(emuR)</a>
<a class="sourceLine" id="cb234-3" data-line-number="3"></a>
<a class="sourceLine" id="cb234-4" data-line-number="4"><span class="co"># create demo data in directory provided by the tempdir() function</span></a>
<a class="sourceLine" id="cb234-5" data-line-number="5"><span class="kw">create_emuRdemoData</span>(<span class="dt">dir =</span> <span class="kw">tempdir</span>())</a>
<a class="sourceLine" id="cb234-6" data-line-number="6"></a>
<a class="sourceLine" id="cb234-7" data-line-number="7"><span class="co"># get the path to a .tpl file of</span></a>
<a class="sourceLine" id="cb234-8" data-line-number="8"><span class="co"># a legacy EMU database that is part of the demo data</span></a>
<a class="sourceLine" id="cb234-9" data-line-number="9">tplPath =<span class="st"> </span><span class="kw">file.path</span>(<span class="kw">tempdir</span>(),</a>
<a class="sourceLine" id="cb234-10" data-line-number="10">                    <span class="st">&quot;emuR_demoData&quot;</span>,</a>
<a class="sourceLine" id="cb234-11" data-line-number="11">                    <span class="st">&quot;legacy_ae&quot;</span>,</a>
<a class="sourceLine" id="cb234-12" data-line-number="12">                    <span class="st">&quot;ae.tpl&quot;</span>)</a>
<a class="sourceLine" id="cb234-13" data-line-number="13"></a>
<a class="sourceLine" id="cb234-14" data-line-number="14"><span class="co"># convert this legacy EMU database to the emuDB format</span></a>
<a class="sourceLine" id="cb234-15" data-line-number="15"><span class="kw">convert_legacyEmuDB</span>(<span class="dt">emuTplPath =</span> tplPath, <span class="dt">targetDir =</span> <span class="kw">tempdir</span>())</a></code></pre></div>
<p>This will create a new <code>emuDB</code> in a temporary directory, provided by R’s <code>tempdir()</code> function, containing all the information specified in the <code>.tpl</code> file. The name of the new <code>emuDB</code> is the same as the basename of the <code>.tpl</code> file from which it was generated. In other words, if the template file of the legacy EMU database has path <code>A</code> and the directory to which the converted database is to be written has path <code>B</code>, then <code>convert_legacyEmuDB(emuTplPath = &quot;A&quot;, targetdir = &quot;B&quot;)</code> will create an <code>emuDB</code> directory in <code>B</code> from the information stored in <code>A</code>.</p>
</div>
<div id="textgrid-collections" class="section level3">
<h3><span class="header-section-number">10.1.2</span> TextGrid collections</h3>
<p>A further function provided is the <code>convert_TextGridCollection()</code> function. This function converts an existing <code>.TextGrid</code> and <code>.wav</code> file collection to the <code>emuDB</code> format. In order to pair the correct files together the <code>.TextGrid</code> files and the <code>.wav</code> files must have the same name (i.e., file name without extension). A further restriction is that the tiers contained within all the <code>.TextGrid</code> files have to be equal in name and type (equal subsets can be chosen using the <code>tierNames</code> argument of the function). For example, if all <code>.TextGrid</code> files contain the tiers <code>Syl: IntervalTier</code>, <code>Phonetic: IntervalTier</code> and <code>Tone: TextTier</code> the conversion will work. However, if a single <code>.TextGrid</code> of the collection has the additional tier <code>Word: IntervalTier</code> the conversion will fail, although it can be made to work by specifying the equal tier subset <code>equalSubset = c('Syl', 'Phonetic', 'Tone')</code> and passing it into the function argument <code>convert\_TextGridCollection(..., tierNames = equalSubset, ...)</code>. R Example <a href="#rexample:emuRpackageDetailsConvTGcol"><strong>??</strong></a> shows how to convert a TextGrid collection to the <code>emuDB</code> format.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb235-1" data-line-number="1"><span class="co"># get the path to a directory containing</span></a>
<a class="sourceLine" id="cb235-2" data-line-number="2"><span class="co"># .wav &amp; .TextGrid files that is part of the demo data</span></a>
<a class="sourceLine" id="cb235-3" data-line-number="3">path2directory =<span class="st"> </span><span class="kw">file.path</span>(<span class="kw">tempdir</span>(),</a>
<a class="sourceLine" id="cb235-4" data-line-number="4">                           <span class="st">&quot;emuR_demoData&quot;</span>,</a>
<a class="sourceLine" id="cb235-5" data-line-number="5">                           <span class="st">&quot;TextGrid_collection&quot;</span>)</a>
<a class="sourceLine" id="cb235-6" data-line-number="6"></a>
<a class="sourceLine" id="cb235-7" data-line-number="7"><span class="co"># convert this TextGridCollection to the emuDB format</span></a>
<a class="sourceLine" id="cb235-8" data-line-number="8"><span class="kw">convert_TextGridCollection</span>(path2directory, <span class="dt">dbName =</span> <span class="st">&quot;myTGcolDB&quot;</span>,</a>
<a class="sourceLine" id="cb235-9" data-line-number="9">                           <span class="dt">targetDir =</span> <span class="kw">tempdir</span>())</a></code></pre></div>
<p>R Example <a href="#rexample:emuRpackageDetailsConvTGcol"><strong>??</strong></a> will create a new <code>emuDB</code> in the directory <code>tempdir()</code> called <code>myTGcolDB</code>. The <code>emuDB</code> will contain all the tier information from the <code>.TextGrid</code> files but will not contain hierarchical information, as <code>.TextGrid</code> files do not contain any linking information. It is worth noting that it is possible to semi-automatically generate links between time-bearing levels using the <code>autobuild_linkFromTimes()</code> function. An example of this was given in Chapter <a href="chap-tutorial.html#chap:tutorial">3</a>.
R Example <a href="#rexample:emuRpackageDetailsConvTGcol"><strong>??</strong></a> creates a new <code>emuDB</code> in the directory <code>tempdir()</code> called <code>myTGcolDB</code>. The <code>emuDB</code> contains all the tier information from the <code>.TextGrid</code> files no hierarchical information, as <code>.TextGrid</code> files do not contain any linking information. Further, it is possible to semi-automatically generate links between time-bearing levels using the <code>autobuild_linkFromTimes()</code> function. An example of this was given in Chapter <a href="chap-tutorial.html#chap:tutorial">3</a>.</p>
</div>
<div id="bpf-collections" class="section level3">
<h3><span class="header-section-number">10.1.3</span> BPF collections</h3>
<p>Similar to the <code>convert_TextGridCollection()</code> function, the <code>emuR</code> package also provides a function for converting file collections consisting of BPF and <code>.wav</code> files to the <code>emuDB</code> format. R Example <a href="#rexample:emuRpackageDetailsConvBPFcol"><strong>??</strong></a> shows how this can be achieved.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" data-line-number="1"><span class="co"># get the path to a directory containing</span></a>
<a class="sourceLine" id="cb236-2" data-line-number="2"><span class="co"># .wav &amp; .par files that is part of the demo data</span></a>
<a class="sourceLine" id="cb236-3" data-line-number="3">path2directory =<span class="st"> </span><span class="kw">file.path</span>(<span class="kw">tempdir</span>(),</a>
<a class="sourceLine" id="cb236-4" data-line-number="4">                           <span class="st">&quot;emuR_demoData&quot;</span>,</a>
<a class="sourceLine" id="cb236-5" data-line-number="5">                           <span class="st">&quot;BPF_collection&quot;</span>)</a>
<a class="sourceLine" id="cb236-6" data-line-number="6"></a>
<a class="sourceLine" id="cb236-7" data-line-number="7"><span class="co"># convert this BPFCollection to the emuDB format</span></a>
<a class="sourceLine" id="cb236-8" data-line-number="8"><span class="kw">convert_BPFCollection</span>(path2directory, <span class="dt">dbName =</span> <span class="st">&#39;myBPF-DB&#39;</span>,</a>
<a class="sourceLine" id="cb236-9" data-line-number="9">                      <span class="dt">targetDir =</span> <span class="kw">tempdir</span>(), <span class="dt">verbose =</span> F)</a></code></pre></div>
<p>As the BPF format also permits annotation items to be linked to one another, this conversion function can optionally preserve this hierarchical information by specifying the <code>refLevel</code> argument.</p>
</div>
<div id="txt-collections" class="section level3">
<h3><span class="header-section-number">10.1.4</span> txt collections</h3>
<p>A further conversion routine provided by the <code>emuR</code> package is the <code>convert_txtCollection()</code> function. As with other file collection conversion functions, it converts file pair collections but this time consisting of plain text <code>.txt</code> and <code>.wav</code> files to the <code>emuDB</code> format. Compared to other conversion routines it behaves slightly differently, as unformatted plain text files do not contain any time information. It therefore places all the annotations of a single <code>.txt</code> file into a single timeless annotation item on a level of type <code>ITEM</code> called <em>bundle</em>.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb237-1" data-line-number="1"><span class="co"># get the path to a directory containing .wav &amp; .par</span></a>
<a class="sourceLine" id="cb237-2" data-line-number="2"><span class="co"># files that is part of the demo data</span></a>
<a class="sourceLine" id="cb237-3" data-line-number="3">path2directory =<span class="st"> </span><span class="kw">file.path</span>(<span class="kw">tempdir</span>(),</a>
<a class="sourceLine" id="cb237-4" data-line-number="4">                           <span class="st">&quot;emuR_demoData&quot;</span>,</a>
<a class="sourceLine" id="cb237-5" data-line-number="5">                           <span class="st">&quot;txt_collection&quot;</span>)</a>
<a class="sourceLine" id="cb237-6" data-line-number="6"></a>
<a class="sourceLine" id="cb237-7" data-line-number="7"><span class="co"># convert this txtCollection to the emuDB format</span></a>
<a class="sourceLine" id="cb237-8" data-line-number="8"><span class="kw">convert_txtCollection</span>(<span class="dt">sourceDir =</span> path2directory,</a>
<a class="sourceLine" id="cb237-9" data-line-number="9">                      <span class="dt">dbName =</span> <span class="st">&quot;txtCol&quot;</span>,</a>
<a class="sourceLine" id="cb237-10" data-line-number="10">                      <span class="dt">targetDir =</span> <span class="kw">tempdir</span>(),</a>
<a class="sourceLine" id="cb237-11" data-line-number="11">                      <span class="dt">attributeDefinitionName =</span> <span class="st">&quot;transcription&quot;</span>,</a>
<a class="sourceLine" id="cb237-12" data-line-number="12">                      <span class="dt">verbose =</span> F)</a></code></pre></div>
<p>Using this conversion routine creates a bare-bone, single route node <code>emuDB</code> which either can be further manually annotated or automatically hierarchically annotated using the <code>runBASwebservice_*</code><a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a> functions of <code>emuR</code>. It is worth noting that these functions are already part of the <code>emuR</code> package; however, they are still considered to have a beta status which is why they are omitted from this documentation. In future versions of this documentation a section or chapter will be dedicated to using the BAS Webservices <span class="citation">(Kisler, Schiel, and Sloetjes <a href="#ref-kisler:2012a">2012</a>)</span> to automatically generate a hierarchical annotation structure for an entire <code>emuDB</code>.</p>
</div>
</div>
<div id="sec:emuRpackageDetails-emuDBinteract" class="section level2">
<h2><span class="header-section-number">10.2</span> <code>emuDB</code> interaction and configuration routines</h2>
<p>This section provides a tabular overview of all the <code>emuDB</code> interaction routines provided by the <code>emuR</code> package and also provides a short description of each function or group of functions.</p>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<table>
<caption>
<span id="tab:emuRpackageDetails-emuDBinteract">Table 10.1: </span>Overview of the <code>emuDB</code> interaction routines provided by <code>emuR</code>.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Functions
</th>
<th style="text-align:left;">
Description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>add/list/remove_attrDefLabelGroup()</code>
</td>
<td style="text-align:left;">
Add / list / remove label group to / of / from <code>attributeDefinition</code> of <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>add/list/remove_labelGroup()</code>
</td>
<td style="text-align:left;">
Add / list / remove global label group to / of / from <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>add/list/remove_levelDefinition()</code>
</td>
<td style="text-align:left;">
Add / list / remove level definition to / of / from <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>add/list/remove_linkDefinition()</code>
</td>
<td style="text-align:left;">
Add / list / remove link definition to / of / from <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>add/list/ remove_ssffTrackDefinition()</code>
</td>
<td style="text-align:left;">
Add / list / remove SSFF track definition to / of / from <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>add/list/rename/remove_attributeDefinition()</code>
</td>
<td style="text-align:left;">
Add / list / rename / remove attribute definition to / of / from <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>add_files()</code>
</td>
<td style="text-align:left;">
Add files to <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>autobuild_linkFromTimes()</code>
</td>
<td style="text-align:left;">
Autobuild links between two levels using their time information <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>create_emuDB()</code>
</td>
<td style="text-align:left;">
Create empty <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>duplicate_level()</code>
</td>
<td style="text-align:left;">
Duplicate level
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>import_mediaFiles()</code>
</td>
<td style="text-align:left;">
Import media files to <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>list_bundles()</code>
</td>
<td style="text-align:left;">
List bundles of <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>list_files()</code>
</td>
<td style="text-align:left;">
List files of <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>list_sessions()</code>
</td>
<td style="text-align:left;">
List sessions of <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>load_emuDB()</code>
</td>
<td style="text-align:left;">
Load <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>replace_itemLabels()</code>
</td>
<td style="text-align:left;">
Replace item labels
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>set/get/remove_legalLabels()</code>
</td>
<td style="text-align:left;">
Set / get / remove legal labels of attribute definition of <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>rename_emuDB()</code>
</td>
<td style="text-align:left;">
Rename <code>emuDB</code>
</td>
</tr>
</tbody>
</table>
</div>
<div id="sec:emuRpackageDetails-emuWebAppConfig" class="section level2">
<h2><span class="header-section-number">10.3</span> <code>EMU-webApp</code> configuration routines</h2>
<p>This section provides a tabular overview of all the <code>EMU-webApp</code> configuration routines provided by the <code>emuR</code> package and also provides a short description of each function or group of functions. See Chapter <a href="chap-emu-webApp.html#chap:emu-webApp">9</a> for examples of how to use these functions.</p>
<table>
<caption>
<span id="tab:emuRpackageDetails-emuWebAppConfig">Table 10.2: </span>Overview of the <code>EMU-webApp</code> configuration functions provided by <code>emuR</code>.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Functions
</th>
<th style="text-align:left;">
Description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>add/list/remove_perspective()</code>
</td>
<td style="text-align:left;">
Add / list / remove perspective to / of / from <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>set/get_levelCanvasesOrder()</code>
</td>
<td style="text-align:left;">
Set / get level canvases order for <code>EMU-webApp</code> of <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>set/get_signalCanvasesOrder()</code>
</td>
<td style="text-align:left;">
Set / get signal canvases order for <code>EMU-webApp</code> of <code>emuDB</code>
</td>
</tr>
</tbody>
</table>
<p>It is worth noting that the legal labels configuration of the <code>emuDB</code> configuration will also affect how the <code>EMU-webApp</code> behaves, as it will not permit any other labels to be entered except those defined as legal labels.</p>
</div>
<div id="sec:emuRpackageDetails-dataExtr" class="section level2">
<h2><span class="header-section-number">10.4</span> Data extraction routines</h2>
<p>This section provides a tabular overview of all the data extraction routines provided by the <code>emuR</code> package and also provides a short description of each function or group of functions. See Chapter <a href="chap-querysys.html#chap:querysys">6</a> and Chapter <a href="chap-sigDataExtr.html#chap:sigDataExtr">7</a> for multiple examples of how the various data extraction routines can be used.</p>
<table>
<caption>
<span id="tab:emuRpackageDetails-dataExtr">Table 10.3: </span>Overview of the data extraction functions provided by <code>emuR</code>.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Functions
</th>
<th style="text-align:left;">
Description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>query()</code>
</td>
<td style="text-align:left;">
Query <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>requery_hier()</code>
</td>
<td style="text-align:left;">
Requery hierarchical context of a segment list in an <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>requery_seq()</code>
</td>
<td style="text-align:left;">
Requery sequential context of segment list in an <code>emuDB</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>get_trackdata()</code>
</td>
<td style="text-align:left;">
Get trackdata from loaded <code>emuDB</code>
</td>
</tr>
</tbody>
</table>
<p>An overview of how the various data extraction functions in the <code>emuR</code> package interact is displayed in Figure <a href="chap-emuRpackageDetails.html#fig:emuRpackageDetails-dataExtrRel">10.1</a>. It is an updated version of a figure presented in <span class="citation">Harrington (<a href="#ref-harrington:2010a">2010</a>)</span> on page 121 that additionally shows the output type of various post-processing functions (e.g., <code>dcut()</code>).</p>
<div class="figure" style="text-align: center"><span id="fig:emuRpackageDetails-dataExtrRel"></span>
<img src="pics/keyFuncsRel.png" alt="Relationship between various key functions in `emuR` and their output. Figure is an updated version of Figure 5.7 in @harrington:2010a on page 121." width="75%" />
<p class="caption">
Figure 10.1: Relationship between various key functions in <code>emuR</code> and their output. Figure is an updated version of Figure 5.7 in <span class="citation">Harrington (<a href="#ref-harrington:2010a">2010</a>)</span> on page 121.
</p>
</div>
</div>
<div id="sec:emuRpackageDetails-centralObjects" class="section level2">
<h2><span class="header-section-number">10.5</span> Central objects</h2>
<p>This section provides a tabular overview of the central objects provided by the <code>emuR</code> package and also provides a short description of each object. See Chapter <a href="chap-querysys.html#chap:querysys">6</a> and <a href="chap-sigDataExtr.html#chap:sigDataExtr">7</a> for examples of functions returning these objects and how they can be used.</p>
<table>
<caption>
<span id="tab:emuRpackageDetails-centralObjects">Table 10.4: </span>Overview of the central objects of the <code>emuR</code> package.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Object
</th>
<th style="text-align:left;">
Description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>emuRsegs</code>
</td>
<td style="text-align:left;">
A <code>emuR</code> segment list is a list of segment descriptions. Each segment descriptions describes a sequence of annotation items. The list is usually a result of an <code>emuDB</code> query using the <code>query()</code> function.
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>trackdata</code>
</td>
<td style="text-align:left;">
A track data object is the result of <code>get_trackdata()</code> and usually contains the extracted signal data tracks belonging to segments of a segment list.
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>emuRtrackdata</code>
</td>
<td style="text-align:left;">
A <code>emuR</code> track data object is the result of <code>get_trackdata()</code> if the <code>resultType</code> parameter is set to <code>emuRtrackdata</code> or the result of an explicit call to <code>create_emuRtrackdata</code>. Compared to the <code>trackdata</code> object it is a sub-class of a <code>data.table</code>/<code>data.frame</code> which is meant to ease integration with other packages for further processing. It can be viewed as an amalgamation of an <code>emuRsegs</code> and a <code>trackdata</code> object as it contains the information stored in both objects (see also <code>?create_emuRtrackdata()</code>).
</td>
</tr>
</tbody>
</table>
</div>
<div id="sec:emuRpackageDetails-exportRoutines" class="section level2">
<h2><span class="header-section-number">10.6</span> Export routines</h2>
<p>Although associated with data loss, the <code>emuR</code> package provides an export routine to the common TextGrid collection format called <code>export_TextGridCollection()</code>. While exporting is sometimes unavoidable, it is essential that users are aware that exporting to other formats which do not support or only partially support hierarchical annotations structures will lead to the loss of the explicit linking information. Although the <code>autobuild_linkFromTimes()</code> can partially recreate some of the hierarchical structure, it is advised that the export routine be used with extreme caution. R Example <a href="#rexample:emuR-funcsExport"><strong>??</strong></a> shows how <code>export_TextGridCollection()</code> can be used to export the levels <em>Text</em>, <em>Syllable</em> and <em>Phonetic</em> of the <em>ae</em> demo <code>emuDB</code> to a TextGrid collection. Figure <a href="chap-emuRpackageDetails.html#fig:emuRfuncs-msajc003-fromExport">10.2</a> show the content of the created <code>msajc003.TextGrid</code> file as displayed by Praat’s <code>&quot;Draw visible sound and Textgrid...&quot;</code> procedure.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb241-1" data-line-number="1"><span class="co"># get the path to &quot;ae&quot; emuDB</span></a>
<a class="sourceLine" id="cb241-2" data-line-number="2">path2ae =<span class="st"> </span><span class="kw">file.path</span>(<span class="kw">tempdir</span>(), <span class="st">&quot;emuR_demoData&quot;</span>, <span class="st">&quot;ae_emuDB&quot;</span>)</a>
<a class="sourceLine" id="cb241-3" data-line-number="3"></a>
<a class="sourceLine" id="cb241-4" data-line-number="4"><span class="co"># load &quot;ae&quot; emuDB</span></a>
<a class="sourceLine" id="cb241-5" data-line-number="5">ae =<span class="st"> </span><span class="kw">load_emuDB</span>(path2ae)</a>
<a class="sourceLine" id="cb241-6" data-line-number="6"></a>
<a class="sourceLine" id="cb241-7" data-line-number="7"><span class="co"># export the levels &quot;Text&quot;, &quot;Syllable&quot;</span></a>
<a class="sourceLine" id="cb241-8" data-line-number="8"><span class="co"># and &quot;Phonetic&quot; to a TextGrid collection</span></a>
<a class="sourceLine" id="cb241-9" data-line-number="9"><span class="kw">export_TextGridCollection</span>(ae,</a>
<a class="sourceLine" id="cb241-10" data-line-number="10">                          <span class="dt">targetDir =</span> <span class="kw">tempdir</span>(),</a>
<a class="sourceLine" id="cb241-11" data-line-number="11">                          <span class="dt">attributeDefinitionNames =</span> <span class="kw">c</span>(<span class="st">&quot;Text&quot;</span>,</a>
<a class="sourceLine" id="cb241-12" data-line-number="12">                                                       <span class="st">&quot;Syllable&quot;</span>,</a>
<a class="sourceLine" id="cb241-13" data-line-number="13">                                                       <span class="st">&quot;Phonetic&quot;</span>))</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:emuRfuncs-msajc003-fromExport"></span>
<img src="pics/msajc003_fromExport.png" alt="TextGrid annotation generated by the `export_TextGridCollection()` function containing the tiers (from top to bottom): *Text*, *Syllable*, *Phonetic*." width="75%" />
<p class="caption">
Figure 10.2: TextGrid annotation generated by the <code>export_TextGridCollection()</code> function containing the tiers (from top to bottom): <em>Text</em>, <em>Syllable</em>, <em>Phonetic</em>.
</p>
</div>
<p>Depending on user requirements, additional export routines might be added to the <code>emuR</code> in the future.</p>
</div>
<div id="conclusion-6" class="section level2">
<h2><span class="header-section-number">10.7</span> Conclusion</h2>
<p>This chapter provided an overview of the essential functions and central objects, grouped into meaningful categories, provided by the <code>emuR</code> package. It is meant as a quick reference for the user to quickly find functions she or he is interested in.</p>

</div>
</div>



<h3>References</h3>
<div id="refs" class="references">
<div id="ref-kisler:2012a">
<p>Kisler, Thomas, Florian Schiel, and Han Sloetjes. 2012. “Signal Processing via Web Services: The Use Case WebMAUS.” In <em>Proceedings Digital Humanities 2012, Hamburg, Germany</em>, 30–34. Hamburg.</p>
</div>
<div id="ref-harrington:2010a">
<p>Harrington, Jonathan. 2010. <em>Phonetic Analysis of Speech Corpora</em>. John Wiley &amp; Sons.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="21">
<li id="fn21"><p>Functions contributed by Nina Pörner.<a href="chap-emuRpackageDetails.html#fnref21" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-emu-webApp.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-querysys-impl.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/IPS-LMU/The-EMU-SDMS-Manual/edit/master/emuR_funcs.Rmd",
"text": "Edit"
},
"download": ["_main.pdf", "_main.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
